---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "dockerfiledb-service"
  namespace: "default"
  labels:
    app: "dockerfiledb"
spec:
  ports:
  - protocol: "TCP"
    port: 5433
  selector:
    app: "dockerfiledb"
  type: "LoadBalancer"
  loadBalancerIP: ""
